"""Shared typed models for backend payload contracts."""

from .analyst import AnalystOrchestrationResult, AnalystResult
from .decision import (
    ALLOWED_DECISION_CONFIDENCE,
    ALLOWED_DECISION_RECOMMENDATIONS,
    DecisionContext,
    DecisionOutput,
    DecisionReferenceCase,
    MemoryPersistenceAssessment,
    decision_output_instruction_keys,
    decision_output_schema,
    extract_decision_output_contract,
)
from .memory import (
    DecisionMemoryMetadata,
    DecisionMemoryRecord,
    DecisionMemoryValidationExample,
    DecisionMemoryValidationSummary,
)
from .knowledge import KnowledgeDocument, KnowledgeEvidenceItem, RankedKnowledgeDocument
from .observation import (
    CountedLabel,
    DecisionGuidanceObservationMetadata,
    DecisionGuidanceObservationRecord,
    GuidanceObservationPersistenceResult,
    GuidanceObservationSummary,
    GuidancePriorsSummary,
)
from .reflection import (
    CandidateMemorySeed,
    ExecutionSummary,
    ExitContext,
    OutcomeMetrics,
    PostTradeCompletenessResult,
    PostTradeValidationResult,
    RealizedOutcomeSummary,
    ReflectionAnalystSummary,
    ReflectionContext,
    ReflectionOutput,
    ReflectionPersistenceResult,
    ReflectionProfile,
    ReflectionReferenceCase,
)
from .workflow import DecisionRealizationResult, ReflectionPersistenceRunResult

__all__ = [
    "AnalystOrchestrationResult",
    "AnalystResult",
    "CountedLabel",
    "ALLOWED_DECISION_CONFIDENCE",
    "ALLOWED_DECISION_RECOMMENDATIONS",
    "DecisionContext",
    "DecisionOutput",
    "DecisionGuidanceObservationMetadata",
    "DecisionGuidanceObservationRecord",
    "DecisionReferenceCase",
    "DecisionMemoryMetadata",
    "DecisionMemoryRecord",
    "DecisionMemoryValidationExample",
    "DecisionMemoryValidationSummary",
    "KnowledgeDocument",
    "KnowledgeEvidenceItem",
    "RankedKnowledgeDocument",
    "GuidanceObservationPersistenceResult",
    "GuidanceObservationSummary",
    "GuidancePriorsSummary",
    "MemoryPersistenceAssessment",
    "decision_output_instruction_keys",
    "decision_output_schema",
    "extract_decision_output_contract",
    "CandidateMemorySeed",
    "DecisionRealizationResult",
    "ExecutionSummary",
    "ExitContext",
    "OutcomeMetrics",
    "PostTradeCompletenessResult",
    "PostTradeValidationResult",
    "RealizedOutcomeSummary",
    "ReflectionAnalystSummary",
    "ReflectionContext",
    "ReflectionOutput",
    "ReflectionPersistenceRunResult",
    "ReflectionPersistenceResult",
    "ReflectionProfile",
    "ReflectionReferenceCase",
]
